imports = ["git/hooks"]
git.hooks.enable = true
git.hooks.pre-comment = "treefmt"

[devshell]
name = "devshell"

packages = [
  "alejandra",
  "nodePackages.prettier",
  "nodePackages.prettier-plugin-toml",
  "shfmt",
  "treefmt"
]

[[commands]]
name = "switch"
category = "devos"
command = "nix-on-droid switch --flake .#device"
help = "Build and activate configuration."

[[env]]
name = "NODE_PATH"
value = "nodePackages.prettier-plugin-toml/lib/node_modules"