[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--plugin", "prettier-plugin-toml", "--write"]
includes = ["*.md", "*.yaml", "*.toml", "*.json"]

[formatter.shell]
command = "shfmt"
options = [ "-i", "2", "-s", "-w" ]
includes = ["*.sh", "*.zsh"]