name: Build and test flake outputs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        devicename:
          - oneplus5
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = aarch64-linux
      - name: Check nix configuration
        run: |
          nix flake check --no-build
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: nix-actions
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          extraPullNames: nix-community,nix-on-droid
      - name: Build ${{ matrix.devicename }} configuration
        run: |
          nix -L --keep-going --show-trace \
            build --impure \
            .#nixOnDroidConfigurations.${{ matrix.devicename }}.activationPackage
