name: CI

on:
  push:
  pull_request:

jobs:
  build-host:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2.0.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: cachix/cachix-action@v10
        with:
          name: actoriu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community,nix-on-droid
      - name: build-host
        uses: nick-invision/retry@v2
        with:
          max_attempts: 2
          timeout_minutes: 720
          retry_on: error
          command: |
            cachix watch-exec actoriu -- \
            nix \
              --log-format bar-with-logs \
              --option keep-going true \
              --show-trace \
              build .#nixOnDroidConfigurations.oneplus5.activationPackage --impure
