name: CI

on:
  push:
  pull_request:

jobs:
  build-host:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1.2.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: cachix/cachix-action@v10
        with:
          name: actoriu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: actoriu,nix-community,nix-on-droid
      - name: build-host
        run: |
          cachix watch-exec actoriu -- \
            nix run nixpkgs#nix-build-uncached -- \
              --keep-going \
              .#nixOnDroidConfigurations.oneplus5.activationPackage --impure 
